# Generated by Django 4.0.3 on 2022-04-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, choices=[('M', 'men'), ('W', 'women'), ('J', 'Junior')], max_length=200, null=True),
        ),
    ]
