export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const WISH_LIST_REQUEST = 'WISH_LIST_REQUEST'
export const WISH_LIST_SUCCESS = 'WISH_LIST_SUCCESS'
export const WISH_LIST_FAIL = 'WISH_LIST_FAIL'

export const TYPE_LIST_REQUEST = 'TYPE_LIST_REQUEST'
export const TYPE_LIST_SUCCESS = 'TYPE_LIST_SUCCESS'
export const TYPE_LIST_FAIL = 'TYPE_LIST_FAIL'


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const ADDTOWISHLIST_FAIL = 'ADDTOWISHLIST_FAIL'
export const ADDTOWISHLIST_REQUEST = 'ADDTOWISHLIST_REQUEST'
export const ADDTOWISHLIST_SUCCESS = 'ADDTOWISHLIST_SUCCESS'


export const DEL_TO_WISHLIST_FAIL = 'DEL_TO_WISHLIST_FAIL'
export const DEL_TO_WISHLIST_REQUEST = 'DEL_TO_WISHLIST_REQUEST'
export const DEL_TO_WISHLIST_SUCCESS = 'DEL_TO_WISHLIST_SUCCESS'


export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'